[package]
name = "hamming-benchmark-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitarray = "0.10.0"
distances = "1.8.0"
hamming = "0.1.3"
simsimd = "6.2.1"
stringzilla = "3.11.1"
triple_accel = "0.4.0"

[target.'cfg(target_arch = "x86")'.dependencies]
hamming_rs = "0.2.22"

[target.'cfg(target_arch = "x86_64")'.dependencies]
hamming_rs = "0.2.22"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }

[[bench]]
name = "hamming"
harness = false
